import { SequenceState } from '@prisma/client'

export const VALID_TRANSITIONS: Record<SequenceState, SequenceState[]> = {
  SCHEDULED: ['SENT_SOFT', 'AUTOPILOT_OFF'],
  SENT_SOFT: ['SENT_FIRM', 'IN_CONVERSATION', 'AUTOPILOT_OFF', 'ESCALATED_TO_HUMAN'],
  SENT_FIRM: ['SENT_FINAL', 'IN_CONVERSATION', 'AUTOPILOT_OFF', 'ESCALATED_TO_HUMAN'],
  SENT_FINAL: ['ESCALATED_TO_HUMAN', 'IN_CONVERSATION', 'AUTOPILOT_OFF'],
  IN_CONVERSATION: ['AWAITING_ACCOUNTANT', 'SENT_SOFT', 'SENT_FIRM', 'SENT_FINAL', 'ESCALATED_TO_HUMAN', 'AUTOPILOT_OFF', 'PAID'],
  AWAITING_ACCOUNTANT: ['PAID', 'PARTIAL_PAID_CONTINUING', 'IN_CONVERSATION', 'ESCALATED_TO_HUMAN'],
  PAID: ['CLOSED'],
  PARTIAL_PAID_CONTINUING: ['SENT_SOFT', 'SENT_FIRM', 'SENT_FINAL', 'IN_CONVERSATION', 'AUTOPILOT_OFF'],
  ESCALATED_TO_HUMAN: ['CLOSED', 'SENT_SOFT', 'IN_CONVERSATION'],
  AUTOPILOT_OFF: ['SENT_SOFT', 'SENT_FIRM', 'SENT_FINAL', 'IN_CONVERSATION', 'CLOSED'],
  CLOSED: [],
}

export function isValidTransition(from: SequenceState, to: SequenceState): boolean {
  return VALID_TRANSITIONS[from].includes(to)
}
